import type {
  PipelineSegment,
  Station,
  Sensor,
  OilBatch,
  Alert,
  Incident,
} from "./types";

/** Demo corridor: Escravos–Warri–Kaduna trunk (simplified coordinates) */
const ROUTE: [number, number][] = [
  [5.48, 5.75],
  [5.52, 5.82],
  [5.58, 5.95],
  [5.65, 6.12],
  [5.72, 6.28],
  [5.78, 6.45],
  [5.85, 6.62],
  [5.92, 6.78],
  [6.0, 6.95],
  [6.08, 7.12],
  [6.15, 7.28],
  [6.22, 7.45],
  [6.3, 7.62],
  [6.38, 7.78],
  [6.45, 7.95],
  [6.52, 8.12],
  [6.6, 8.28],
  [6.68, 8.45],
  [6.75, 8.62],
  [6.82, 8.78],
  [6.9, 8.95],
  [6.98, 9.12],
  [7.05, 9.28],
  [7.12, 9.45],
  [7.2, 9.62],
  [7.28, 9.78],
  [7.35, 9.95],
  [7.42, 10.12],
  [7.5, 10.28],
  [7.58, 10.45],
  [7.65, 10.62],
  [7.72, 10.78],
  [7.8, 10.95],
];

function toGeo(i: number): { lat: number; lng: number } {
  const [lat, lng] = ROUTE[i] ?? ROUTE[ROUTE.length - 1];
  return { lat, lng };
}

function sliceRoute(start: number, end: number) {
  return ROUTE.slice(start, end + 1).map(([lat, lng]) => ({ lat, lng }));
}

export const PIPELINE_SEGMENTS: PipelineSegment[] = [
  {
    id: "seg-001",
    name: "Escravos Terminal — Delta Junction",
    from: "Escravos",
    to: "Delta Junction",
    coordinates: sliceRoute(0, 7),
    lengthKm: 42,
    diameterMm: 610,
    capacityBpd: 180000,
    status: "operational",
  },
  {
    id: "seg-002",
    name: "Delta Junction — Benin Ridge",
    from: "Delta Junction",
    to: "Benin Ridge",
    coordinates: sliceRoute(7, 14),
    lengthKm: 38,
    diameterMm: 610,
    capacityBpd: 180000,
    status: "operational",
  },
  {
    id: "seg-003",
    name: "Benin Ridge — Auchi Pass",
    from: "Benin Ridge",
    to: "Auchi Pass",
    coordinates: sliceRoute(14, 21),
    lengthKm: 45,
    diameterMm: 508,
    capacityBpd: 150000,
    status: "degraded",
  },
  {
    id: "seg-004",
    name: "Auchi Pass — Lokoja Hub",
    from: "Auchi Pass",
    to: "Lokoja Hub",
    coordinates: sliceRoute(21, 28),
    lengthKm: 52,
    diameterMm: 508,
    capacityBpd: 150000,
    status: "operational",
  },
  {
    id: "seg-005",
    name: "Lokoja Hub — Kaduna Terminal",
    from: "Lokoja Hub",
    to: "Kaduna Terminal",
    coordinates: sliceRoute(28, 31),
    lengthKm: 28,
    diameterMm: 406,
    capacityBpd: 120000,
    status: "operational",
  },
];

export const STATIONS: Station[] = [
  {
    id: "st-escravos",
    name: "Escravos Export Terminal",
    type: "storage",
    position: toGeo(0),
    segmentId: "seg-001",
    status: "operational",
    powerBackup: true,
    powerOnline: true,
  },
  {
    id: "st-pump-1",
    name: "Pump Station Alpha",
    type: "pump",
    position: toGeo(4),
    segmentId: "seg-001",
    status: "operational",
    powerBackup: true,
    powerOnline: true,
  },
  {
    id: "st-valve-1",
    name: "Block Valve BV-12",
    type: "valve",
    position: toGeo(10),
    segmentId: "seg-002",
    status: "operational",
    powerBackup: false,
    powerOnline: true,
  },
  {
    id: "st-meter-1",
    name: "Custody Meter CM-07",
    type: "metering",
    position: toGeo(16),
    segmentId: "seg-003",
    status: "degraded",
    powerBackup: true,
    powerOnline: false,
  },
  {
    id: "st-pump-2",
    name: "Pump Station Bravo",
    type: "pump",
    position: toGeo(22),
    segmentId: "seg-004",
    status: "operational",
    powerBackup: true,
    powerOnline: true,
  },
  {
    id: "st-sub-1",
    name: "Substation SS-North",
    type: "substation",
    position: toGeo(26),
    segmentId: "seg-004",
    status: "operational",
    powerBackup: true,
    powerOnline: true,
  },
  {
    id: "st-kaduna",
    name: "Kaduna Refinery Intake",
    type: "storage",
    position: toGeo(31),
    segmentId: "seg-005",
    status: "operational",
    powerBackup: true,
    powerOnline: true,
  },
];

function makeSensor(
  id: string,
  segmentId: string,
  type: Sensor["type"],
  label: string,
  routeIndex: number,
  unit: string,
  value: number,
  baseline: number,
  warn: number,
  critical: number,
  stationId?: string
): Sensor {
  return {
    id,
    segmentId,
    stationId,
    type,
    label,
    position: toGeo(routeIndex),
    unit,
    value,
    baseline,
    threshold: { warn, critical },
    status: "operational",
    lastUpdated: new Date().toISOString(),
  };
}

export const INITIAL_SENSORS: Sensor[] = [
  makeSensor("sns-p-001", "seg-001", "pressure", "Line pressure T1", 2, "bar", 42.5, 42, 48, 55),
  makeSensor("sns-f-001", "seg-001", "flow", "Flow rate T1", 3, "m³/h", 1250, 1200, 1400, 1600),
  makeSensor("sns-t-001", "seg-002", "temperature", "Crude temp", 9, "°C", 38.2, 35, 55, 65),
  makeSensor("sns-v-001", "seg-002", "vibration", "Pump vibration", 10, "mm/s", 2.1, 2, 4, 6, "st-valve-1"),
  makeSensor("sns-a-001", "seg-003", "acoustic", "Leak acoustic", 15, "dB", 28, 25, 40, 55),
  makeSensor("sns-g-001", "seg-003", "ground_penetration", "Ground intrusion", 17, "N", 120, 100, 200, 350),
  makeSensor("sns-fn-001", "seg-003", "fence", "Perimeter fence", 18, "—", 0, 0, 1, 1),
  makeSensor("sns-p-002", "seg-004", "pressure", "Line pressure T2", 23, "bar", 39.8, 40, 48, 55),
  makeSensor("sns-pw-001", "seg-004", "power", "Grid supply", 26, "kV", 33, 33, 30, 25, "st-sub-1"),
  makeSensor("sns-f-002", "seg-005", "flow", "Terminal intake", 30, "m³/h", 980, 950, 1150, 1300),
];

export const INITIAL_OIL_BATCHES: OilBatch[] = [
  {
    id: "batch-4412",
    label: "Bonny Light — Batch 4412",
    origin: "Escravos",
    destination: "Kaduna Refinery",
    volumeBbl: 42000,
    apiGravity: 35.2,
    sulfurPct: 0.14,
    currentSegmentId: "seg-003",
    progressPct: 58,
    etaHours: 18.5,
    status: "in_transit",
    startedAt: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
  {
    id: "batch-4413",
    label: "Escravos Blend — Batch 4413",
    origin: "Escravos",
    destination: "Warri Depot",
    volumeBbl: 28500,
    apiGravity: 32.8,
    sulfurPct: 0.22,
    currentSegmentId: "seg-001",
    progressPct: 22,
    etaHours: 42,
    status: "in_transit",
    startedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: "alt-001",
    category: "leak",
    severity: "high",
    title: "Acoustic anomaly — possible leak",
    message:
      "Acoustic sensor sns-a-001 detected sustained high-frequency signature consistent with pinhole leak near km 87.",
    segmentId: "seg-003",
    sensorId: "sns-a-001",
    position: toGeo(15),
    acknowledged: false,
    resolved: false,
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: "alt-002",
    category: "vandalism",
    severity: "critical",
    title: "Fence breach — unauthorized access",
    message:
      "Perimeter fence sensor triggered at Auchi Pass. Ground penetration sensor corroborates excavation activity.",
    segmentId: "seg-003",
    sensorId: "sns-fn-001",
    position: toGeo(18),
    acknowledged: false,
    resolved: false,
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: "alt-003",
    category: "power",
    severity: "high",
    title: "Substation offline — CM-07 on backup",
    message:
      "Grid supply at SS-North dropped below threshold. Custody metering station running on UPS; estimated 4h runtime.",
    segmentId: "seg-004",
    stationId: "st-meter-1",
    sensorId: "sns-pw-001",
    position: toGeo(16),
    acknowledged: true,
    resolved: false,
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: "alt-004",
    category: "theft",
    severity: "medium",
    title: "Flow imbalance — suspected hot-tap",
    message:
      "Metered outflow 3.2% below upstream custody total over 6h window. Investigation recommended at Benin Ridge.",
    segmentId: "seg-002",
    position: toGeo(11),
    acknowledged: false,
    resolved: false,
    createdAt: new Date(Date.now() - 360 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60000).toISOString(),
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: "inc-001",
    alertId: "alt-002",
    type: "vandalism",
    status: "investigating",
    assignedTo: "Field Team Delta-4",
    notes: "Drone dispatched. SCADA isolation valve BV-12 on standby.",
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: "inc-002",
    alertId: "alt-001",
    type: "leak",
    status: "open",
    assignedTo: "Integrity Unit",
    notes: "Pressure hold test scheduled. Pig run deferred.",
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
  },
];
